/* Copyright 2020-2023 The MathWorks, Inc. */

#ifndef UORBMETADATA_H
#define UORBMETADATA_H

#include "customFunction.h"
#include <uORB/topics/action_request.h>
#include <uORB/topics/actuator_armed.h>
#include <uORB/topics/actuator_controls_status.h>
#include <uORB/topics/actuator_motors.h>
#include <uORB/topics/actuator_outputs.h>
#include <uORB/topics/actuator_servos.h>
#include <uORB/topics/actuator_servos_trim.h>
#include <uORB/topics/actuator_test.h>
#include <uORB/topics/adc_report.h>
#include <uORB/topics/airspeed.h>
#include <uORB/topics/airspeed_validated.h>
#include <uORB/topics/airspeed_wind.h>
#include <uORB/topics/autotune_attitude_control_status.h>
#include <uORB/topics/battery_status.h>
#include <uORB/topics/button_event.h>
#include <uORB/topics/camera_capture.h>
#include <uORB/topics/camera_status.h>
#include <uORB/topics/camera_trigger.h>
#include <uORB/topics/cellular_status.h>
#include <uORB/topics/collision_constraints.h>
#include <uORB/topics/collision_report.h>
#include <uORB/topics/control_allocator_status.h>
#include <uORB/topics/cpuload.h>
#include <uORB/topics/debug_array.h>
#include <uORB/topics/debug_key_value.h>
#include <uORB/topics/debug_value.h>
#include <uORB/topics/debug_vect.h>
#include <uORB/topics/differential_pressure.h>
#include <uORB/topics/distance_sensor.h>
#include <uORB/topics/ekf2_timestamps.h>
#include <uORB/topics/esc_report.h>
#include <uORB/topics/esc_status.h>
#include <uORB/topics/estimator_aid_source1d.h>
#include <uORB/topics/estimator_aid_source2d.h>
#include <uORB/topics/estimator_aid_source3d.h>
#include <uORB/topics/estimator_bias.h>
#include <uORB/topics/estimator_bias3d.h>
#include <uORB/topics/estimator_event_flags.h>
#include <uORB/topics/estimator_gps_status.h>
#include <uORB/topics/estimator_innovations.h>
#include <uORB/topics/estimator_selector_status.h>
#include <uORB/topics/estimator_sensor_bias.h>
#include <uORB/topics/estimator_states.h>
#include <uORB/topics/estimator_status.h>
#include <uORB/topics/estimator_status_flags.h>
#include <uORB/topics/event.h>
#include <uORB/topics/failsafe_flags.h>
#include <uORB/topics/failure_detector_status.h>
#include <uORB/topics/follow_target.h>
#include <uORB/topics/follow_target_estimator.h>
#include <uORB/topics/follow_target_status.h>
#include <uORB/topics/generator_status.h>
#include <uORB/topics/geofence_result.h>
#include <uORB/topics/gimbal_controls.h>
#include <uORB/topics/gimbal_device_attitude_status.h>
#include <uORB/topics/gimbal_device_information.h>
#include <uORB/topics/gimbal_device_set_attitude.h>
#include <uORB/topics/gimbal_manager_information.h>
#include <uORB/topics/gimbal_manager_set_attitude.h>
#include <uORB/topics/gimbal_manager_set_manual_control.h>
#include <uORB/topics/gimbal_manager_status.h>
#include <uORB/topics/gps_dump.h>
#include <uORB/topics/gps_inject_data.h>
#include <uORB/topics/gripper.h>
#include <uORB/topics/health_report.h>
#include <uORB/topics/heater_status.h>
#include <uORB/topics/home_position.h>
#include <uORB/topics/hover_thrust_estimate.h>
#include <uORB/topics/input_rc.h>
#include <uORB/topics/internal_combustion_engine_status.h>
#include <uORB/topics/iridiumsbd_status.h>
#include <uORB/topics/irlock_report.h>
#include <uORB/topics/landing_gear.h>
#include <uORB/topics/landing_gear_wheel.h>
#include <uORB/topics/landing_target_innovations.h>
#include <uORB/topics/landing_target_pose.h>
#include <uORB/topics/launch_detection_status.h>
#include <uORB/topics/led_control.h>
#include <uORB/topics/log_message.h>
#include <uORB/topics/logger_status.h>
#include <uORB/topics/mag_worker_data.h>
#include <uORB/topics/magnetometer_bias_estimate.h>
#include <uORB/topics/manual_control_setpoint.h>
#include <uORB/topics/manual_control_switches.h>
#include <uORB/topics/mavlink_log.h>
#include <uORB/topics/mavlink_tunnel.h>
#include <uORB/topics/mission.h>
#include <uORB/topics/mission_result.h>
#include <uORB/topics/mode_completed.h>
#include <uORB/topics/mount_orientation.h>
#include <uORB/topics/navigator_mission_item.h>
#include <uORB/topics/normalized_unsigned_setpoint.h>
#include <uORB/topics/npfg_status.h>
#include <uORB/topics/obstacle_distance.h>
#include <uORB/topics/offboard_control_mode.h>
#include <uORB/topics/onboard_computer_status.h>
#include <uORB/topics/orb_test.h>
#include <uORB/topics/orb_test_large.h>
#include <uORB/topics/orb_test_medium.h>
#include <uORB/topics/orbit_status.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/ping.h>
#include <uORB/topics/position_controller_landing_status.h>
#include <uORB/topics/position_controller_status.h>
#include <uORB/topics/position_setpoint.h>
#include <uORB/topics/position_setpoint_triplet.h>
#include <uORB/topics/power_button_state.h>
#include <uORB/topics/power_monitor.h>
#include <uORB/topics/pps_capture.h>
#include <uORB/topics/pwm_input.h>
#include <uORB/topics/px4io_status.h>
#include <uORB/topics/qshell_req.h>
#include <uORB/topics/qshell_retval.h>
#include <uORB/topics/radio_status.h>
#include <uORB/topics/rate_ctrl_status.h>
#include <uORB/topics/rc_channels.h>
#include <uORB/topics/rc_parameter_map.h>
#include <uORB/topics/rpm.h>
#include <uORB/topics/rtl_time_estimate.h>
#include <uORB/topics/satellite_info.h>
#include <uORB/topics/sensor_accel.h>
#include <uORB/topics/sensor_accel_fifo.h>
#include <uORB/topics/sensor_baro.h>
#include <uORB/topics/sensor_combined.h>
#include <uORB/topics/sensor_correction.h>
#include <uORB/topics/sensor_gnss_relative.h>
#include <uORB/topics/sensor_gps.h>
#include <uORB/topics/sensor_gyro.h>
#include <uORB/topics/sensor_gyro_fft.h>
#include <uORB/topics/sensor_gyro_fifo.h>
#include <uORB/topics/sensor_hygrometer.h>
#include <uORB/topics/sensor_mag.h>
#include <uORB/topics/sensor_optical_flow.h>
#include <uORB/topics/sensor_preflight_mag.h>
#include <uORB/topics/sensor_selection.h>
#include <uORB/topics/sensor_uwb.h>
#include <uORB/topics/sensors_status.h>
#include <uORB/topics/sensors_status_imu.h>
#include <uORB/topics/system_power.h>
#include <uORB/topics/takeoff_status.h>
#include <uORB/topics/task_stack_info.h>
#include <uORB/topics/tecs_status.h>
#include <uORB/topics/telemetry_status.h>
#include <uORB/topics/tiltrotor_extra_controls.h>
#include <uORB/topics/timesync_status.h>
#include <uORB/topics/trajectory_bezier.h>
#include <uORB/topics/trajectory_setpoint.h>
#include <uORB/topics/trajectory_waypoint.h>
#include <uORB/topics/transponder_report.h>
#include <uORB/topics/tune_control.h>
#include <uORB/topics/uavcan_parameter_request.h>
#include <uORB/topics/uavcan_parameter_value.h>
#include <uORB/topics/ulog_stream.h>
#include <uORB/topics/ulog_stream_ack.h>
#include <uORB/topics/vehicle_acceleration.h>
#include <uORB/topics/vehicle_air_data.h>
#include <uORB/topics/vehicle_angular_acceleration_setpoint.h>
#include <uORB/topics/vehicle_angular_velocity.h>
#include <uORB/topics/vehicle_attitude.h>
#include <uORB/topics/vehicle_attitude_setpoint.h>
#include <uORB/topics/vehicle_command.h>
#include <uORB/topics/vehicle_command_ack.h>
#include <uORB/topics/vehicle_constraints.h>
#include <uORB/topics/vehicle_control_mode.h>
#include <uORB/topics/vehicle_global_position.h>
#include <uORB/topics/vehicle_imu.h>
#include <uORB/topics/vehicle_imu_status.h>
#include <uORB/topics/vehicle_land_detected.h>
#include <uORB/topics/vehicle_local_position.h>
#include <uORB/topics/vehicle_local_position_setpoint.h>
#include <uORB/topics/vehicle_magnetometer.h>
#include <uORB/topics/vehicle_odometry.h>
#include <uORB/topics/vehicle_optical_flow.h>
#include <uORB/topics/vehicle_optical_flow_vel.h>
#include <uORB/topics/vehicle_rates_setpoint.h>
#include <uORB/topics/vehicle_roi.h>
#include <uORB/topics/vehicle_status.h>
#include <uORB/topics/vehicle_thrust_setpoint.h>
#include <uORB/topics/vehicle_torque_setpoint.h>
#include <uORB/topics/vehicle_trajectory_bezier.h>
#include <uORB/topics/vehicle_trajectory_waypoint.h>
#include <uORB/topics/vtol_vehicle_status.h>
#include <uORB/topics/wind.h>
#include <uORB/topics/yaw_estimator_status.h>

#ifdef __cplusplus
extern "C" { /* sbcheck:ok:extern_c */
#endif
orb_metadata_t* getorbData(uint8_T uORBID);
#ifdef __cplusplus
}
#endif

#endif
